### ISSUE TITLE
modal

### ISSUE THREAD

**Issue by maschuep** [m-cirkovic/Open-Data_ASTRA#29]
- [x] falls kein schwerverkehr und kein leichtverkehr lösung
- [x] grösse von Modal kleiner
- [x] Modal verkleinern

**Comment by maschuep** [comment]
Neues Design?
Vorschläge:
- Tabelle
- Diagramm

**Comment by maschuep** [comment]
- [ ] zweidimensionale charts (geschw, anzahl fahrzeuge)
- [ ] tacho
- [ ] fanchart

**Comment by maschuep** [comment]
**Idee**
Spuren darstellen, kleine Kreise als Autos und grosse als Lastwagen. 
Geschwindigkeit auch als Geschwindikeit der Punkte dargestellt. 
Fahrzeuge pro Stunde werden durch Anzahl Punkte dargestellt.

**Comment by maschuep** [comment]
Idee 
2d-Plot
Fahrzeugtyp: Grösse der Kreise
Spur: Farbe
Geschw: x-achse
Fahrzeug/h: y-achse oder anzahl kreise

**Comment by maschuep** [comment]
- [x]  Fahrzeuge / h anzeigen

**Comment by m-cirkovic** [comment]
> 
> 
>     * [ ]  falls kein schwerverkehr und kein leichtverkehr lösung
> 
>     * [x]  grösse von Modal kleiner
> 
>     * [x]  Modal verkleinern

Es gibt keine Punkte, wenn es keine Fahrzeuge hat
