### ISSUE TITLE
Rankings und Infos

### ISSUE THREAD

**Issue by maschuep** [m-cirkovic/Open-Data_ASTRA#31]
- [x] Anzahl Messtellen
- [x] Anzahl Messungen
- [x] Total Verkehr
- [x] Top 10 Stellen mit meistem Verkehr
     - [x] Müsste mit map verbunden werden 
- [x]  schnellste & langsamste geschwindigkeit
- [x] # messstellen über 120
- [x] meister verkehr
- [x] Infoicon für allgemeine Daten um zu spezifizieren welche erklären was die spezifischen Daten sind

**Comment by m-cirkovic** [comment]
Die Daten in "Allgemeinen Daten" sind sehr unklar: Sind sie aktuell oder der Durchschnitt oder ...
