### ISSUE TITLE
modal improvement ideas

### ISSUE THREAD

**Issue by maschuep** [m-cirkovic/Open-Data_ASTRA#36]
- [x] werte noch anzeigen (info icon)
- [x] spuren näher beieinander

**Comment by m-cirkovic** [comment]
Die Spuren würde ich nicht näher beieinander haben. Aber wir können noch darüber diskutieren.
Was genau meinst du mit mit dem ersten Punkt?

**Comment by maschuep** [comment]
Mit dem ersten Punkt meine ich, dass die Zahlen für Fahrzeug/h und km/h angezeigt werden sollten.
