### ISSUE TITLE
Messtellen verschiedene Spuren zusammenfassen

### ISSUE THREAD

**Issue by maschuep** [m-cirkovic/Open-Data_ASTRA#9]
Die Messtellen und Messungen haben eine Id: `CH:123.00` dabei ist diese für jede Spur eindeutig. Man sollte sie mit dem Locationcode aus Issue #5 zusammenfassen und so die Übersicht besser machen.

Fragen: 
- [x] Daten aller Lanes zusammenfassen und darstellen
- [x] Daten einzelner Lanes anzeigen
- [x] beides? (Es ist ja eigentlich schade die Granularität zu verlieren)

**Comment by maschuep** [comment]
- [x] Die Messtellen werden noch nicht ganz korrekt nach Error und normal gefiltert.
    - [x] Manche Messtellen tauchen in beiden layers afu
    - [x] Was wenn in einer specificLocation eine Lane ein Error hat aber andere funktionieren

**Comment by m-cirkovic** [comment]
- [ ] Modal und die Darstellung der Spuren schöner machen
